server {
    listen 80;

    location /proxy {
        proxy_pass http://proxy:4000;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
